### ISSUE TITLE
Trying to use Add but getting issue as Invalid callback?

### ISSUE THREAD

**Issue by amruta21** [kursion/dbfeazy#1]
fs.js:143
  throw new ERR_INVALID_CALLBACK(cb);
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received 'utf8'
    at maybeCallback (fs.js:143:9)
    at Object.writeFile (fs.js:1251:14)
    at DBFeazy.module.exports.DBFeazy.opline_log (C:\workspace\Personal\practice\siba\node_modules\dbfeazy\build\index.js:101:17)
    at DBFeazy.module.exports.DBFeazy.Add (C:\workspace\Personal\practice\siba\node_modules\dbfeazy\build\index.js:181:12)
    at Object.<anonymous> (C:\workspace\Personal\practice\siba\connection.js:5:5)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'ERR_INVALID_CALLBACK'
}
Below is my code 
```
var DBFeazy = require('dbfeazy');
console.log()
 var db = new DBFeazy("user");
 db.Add("age", 27);
 db.Save();
 console.log(db.Get("age"));
```

**Comment by kursion** [comment]
Thanks for the feedback. I have published v1.0.4 which should have fixed the issue. 

Please feel free to 

```
$ rm -rf node_modules package-lock.json
$ npm install
```

I have also update the example to be in JavaScript rather than coffeeScript.

**Comment by amruta21** [comment]
@kursion Tried same but not working 
```

fs.js:143
  throw new ERR_INVALID_CALLBACK(cb);
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received 'utf8'
    at maybeCallback (fs.js:143:9)
    at Object.writeFile (fs.js:1251:14)
    at DBFeazy.module.exports.DBFeazy.opline_log (C:\workspace\Personal\practice\dbfeasy\node_modules\dbfeazy
\build\index.js:101:17)
    at DBFeazy.module.exports.DBFeazy.Add (C:\workspace\Personal\practice\dbfeasy\node_modules\dbfeazy\build\
index.js:181:12)
    at Object.<anonymous> (C:\workspace\Personal\practice\dbfeasy\index.js:10:4)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'ERR_INVALID_CALLBACK'
}
```

Getting same error


I have just followed following steps:

1. created project with npm start
2. then "npm i dbfeasy"
3. then added code 
```
var DBFeazy = require('dbfeazy');
console.log()
 var db = new DBFeazy("user");
 db.Add("age", 27);
 db.Save();
 console.log(db.Get("age"));
```
and getting above error

**Comment by kursion** [comment]
Yes got the same issue as you do. Checking

**Comment by kursion** [comment]
My bad, I forgot to `make build`
Try with 1.0.6
It works for me. Your code prints: 27

**Comment by amruta21** [comment]
It worked for me .. Thanks .. But I can see json in dbf file.

**Comment by kursion** [comment]
Are you sure that you are looking at the correct file ? I'm having

`{"age": 28} ` in my user.dbf file. 

I also ran the test and all of them works.

**Comment by kursion** [comment]
![Annotation 2020-04-20 191018](https://user-images.githubusercontent.com/1087731/79779368-9a66ed80-833a-11ea-9499-fe7edcedecbf.png)

**Comment by kursion** [comment]
I have checked and the writings are synchrous so it should work. Here is another example:
![Annotation 2020-04-20 191443](https://user-images.githubusercontent.com/1087731/79779803-3e509900-833b-11ea-9814-5e63ca678156.png)

Don't forget to db.Restore() if needed

**Comment by amruta21** [comment]
@kursion But we should not see this as json right??

I am not able to see values in file  in https://www.dbfopener.com/

**Comment by kursion** [comment]
Yes, it is saved as JSON. The extension was chosen a bit randomly
